version: 2.1

jobs:
  run-script:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: python main.py

workflows:
  version: 2
  run-on-current-branch:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - << pipeline.git.branch >>
    jobs:
      - run-script
