version: 2.1

jobs:
  run-script:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: python main.py

workflows:
  version: 2
  run-on-current-branch:
    jobs:
      - run-script
