version: 2.1

jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script every 5 minutes
          command: |
            while true; do
              python3 main.py
              sleep 300  # 300 seconds = 5 minutes
            done

workflows:
  version: 2
  commit-workflow:
    jobs:
      - BotMonitoring
  schedule-BotMonitoring:
    triggers:
      - schedule:
          cron: "0 * * * *"  # Trigger every hour
          filters:
            branches:
              only:
                - main
    jobs:
      - BotMonitoring
