version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  version: 2
  scheduled-hello:
    triggers:
      - schedule:
          cron: "*/5 * * * *" # Runs every 5 minutes
          filters:
            branches:
              only:
                - main # Set to the branch you want this schedule to run on
    jobs:
      - say-hello
